# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/payment_gateways/Mollie" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/payment_gateways/braintree" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/payment_gateways/fondy" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/payment_gateways/instamojo" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/payment_gateways/mercadopago" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/payment_gateways/stripe" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/payment_gateways/sumup" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/dompdf" # Location of package manifests
    schedule:
      interval: "weekly"
